version: "3"

services:
  code-server:
    build: .
    ports:
      - "1337:8080"
    volumes:
      - "${PWD}:/home/coder/project"
      - "${HOME}/.local/share/code-server:/home/coder/.local/share/code-server"
    environment:
      PASSWORD: ${PASSWORD}